### ISSUE TITLE
stage-0 problem

### ISSUE THREAD

**Issue by Grahack** [fraserxu/react-dropdown#74]
Hi,
Sorry, I'm quite novice to all these technologies.
I got this error: `couldn't find preset stage-0` and had to:

    npm install babel-preset-stage-0

to make all this work. Should this be in the docs or could you point me to some articles where I could learn what happened?

Thanks.

**Comment by fraserxu** [comment]
Hmm, I don't think you need install `babel-preset-stage-0` just in order to use this library. But it might be a requirement for setting/running a React project, to be able to parse ES6 + JSX syntax.

If you have a React project already running, there are high chance you have already installed it. You got this error might be because the configuration of your own project, not this library.

The library itself has already compiled with Babel before publishing to npm.

**Comment by Grahack** [comment]
OK thank you for your answer and thank you for `react-dropdown`.
